version: '3.8'

services:
  api:
    build:
      context: ./pd_web_core
      dockerfile: Dockerfile
    container_name: pd-api
    ports:
      - "8000:8000"
    volumes:
      - ./pd_web_core:/var/www/html
    depends_on:
      - db
    command: bash -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build:
      context: ./pd_web_ui
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:80"
    depends_on:
      - api

  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_OUTER_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - frontend
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl

volumes:
  pgdata:
    driver: local